name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run test suite'
        required: false
        default: true
        type: boolean
      run_build:
        description: 'Run build process'
        required: false
        default: true
        type: boolean

jobs:
  # Test workflow - comprehensive testing across multiple environments
  test:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_tests }}
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: true
      run-custom-tests: true
    secrets: inherit

  # Build workflow - package building and artifact creation
  build:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_build }}
    uses: ./.github/workflows/build.yml
    needs: test
    with:
      upload-artifacts: true
      verify-package: true
    secrets: inherit

  # Workflow summary and status aggregation
  summary:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: always()
    steps:
      - name: Set summary status
        id: set-summary-status
        shell: bash
        run: |
          echo "## CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Workflow | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|---------|" >> $GITHUB_STEP_SUMMARY
          echo "| Tests | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ needs.test.result }}" == "success" && "${{ needs.build.result }}" == "success" ]]; then
            echo "[PASS] All workflows completed successfully!" >> $GITHUB_STEP_SUMMARY
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "[FAIL] One or more workflows failed" >> $GITHUB_STEP_SUMMARY
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - name: Check overall status
        if: steps.set-summary-status.outputs.status == 'failure'
        run: |
          echo "CI Pipeline failed - check individual workflow results"
          exit 1

  # Post-workflow notifications and cleanup
  notify:
    runs-on: ubuntu-latest
    needs: [summary]
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Workflow notification
        run: |
          echo "CI Pipeline completed for main branch"
          echo "Status: ${{ needs.summary.result }}"
          # Future: Add Slack/email notifications here